#!/bin/bash

log () {
  echo -e "  \E[32m$1\E[0m  $2"
}
export -f log
export PATH=$HOME/bin:$PATH

~/code/dotfiles/lib/prepare
~/code/dotfiles/lib/install_packages

~/code/dotfiles/lib/install_zsh
~/code/dotfiles/lib/install_vim
~/code/dotfiles/lib/install_tmux

~/code/dotfiles/lib/install_rbenv
~/code/dotfiles/lib/install_ruby
~/code/dotfiles/lib/install_gems

~/code/dotfiles/lib/install_dotfiles
~/code/dotfiles/lib/install_vim_plugins
log "done"
