
# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
zstyle ':prezto:module:terminal' auto-title 'no'

autoload -U colors && colors

# Source customizations
for file in $HOME/.zsh/*.zsh; do
  if [ -f "$file" ] ; then
    source "$file"
  fi
done

# use dvorak as the basis for spell checking
# setopt DVORAK
unsetopt correct_all

# start tmux by default
if [[ ! $TERM =~ screen ]]; then
  $(tmux)
fi

# nvm things
export NVM_DIR="$HOME/.nvm"
. "/usr/local/opt/nvm/nvm.sh"

[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm"

# added by travis gem
[ -f /Users/wyang/.travis/travis.sh ] && source /Users/wyang/.travis/travis.sh

# Add RVM to PATH for scripting. Make sure this is the last PATH variable change.
export PATH="$PATH:$HOME/.rvm/bin"
