#!/bin/bash

echo ""
echo "Install packages"
echo ""

# Install git
brew install git

# Install brew
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
