#!/bin/bash

echo ""
echo "Install Vim"
echo ""

brew rm vim macvim python
brew install python
brew install vim --with-override-system-vi
brew install macvim --with-override-system-vim
brew link --overwrite macvim
