#!/bin/bash
set -e

echo ""
echo "Install packages"
echo ""

if ! [ -x "$(command -v brew)" ];
  # Install brew
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
  brew update
fi

if ! [ -x "$(command -v git)" ];
  # Install git
  brew install git
fi
