#!/bin/bash

echo ""
echo "Install vim plugins"
echo ""

# install vim vundle
git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim

# compile YCM
brew install cmake
cd ~/.vim/bundle/YouCompleteMe; ./install.py --clang-completer

# install plugins
mvim -ve +PluginInstall +qall
