#!/bin/bash
set -e

echo ""
echo "Install vim plugins"
echo ""

# install vim vundle
git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim

# compile YCM
brew install cmake mono go nodejs
cd ~/.vim/bundle/YouCompleteMe; python3 install.py --all

# install plugins
vim +PlugInstall +qall
