#!/bin/bash

echo ""
echo "Install vim plugins"
echo ""

# install vim vundle
git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim

# install plugins
vim -e +PluginInstall +qall
# compile plugins
sudo apt-get install -y \
  cmake \
  python-dev
(cd $HOME/.vim/bundle/YouCompleteMe; ./install.sh)
